name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: sudo apt update && sudo apt install -y make gcc libcjson-dev libsdl2-dev libglew-dev
      - name: Build
        run: make -j10
